AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy ALB required by entire stack.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Customer Resource Tags
        Parameters:
          - pmCustomer
          - pmProject
          - pmEnvironment
      - Label:
          default: VPC Configuration Parameters
        Parameters:
          - pmVpc
      - Label:
          default: ALB Configuration Parameters
        Parameters:
          - pmPublicSubnets
          - pmWebServer1
          - pmWebServer2
          - pmSG
    ParameterLabels:
      pmCustomer:
        default: Enter Customer name
      pmProject:
        default: Enter Project name
      pmEnvironment:
        default: Enter Environment name
      pmVpc:
        default: Enter VPC Id
      pmPublicSubnets:
        default: Enter Public subnet list
      pmWebServer1:
        default: Enter WebServer 1 Id
      pmWebServer2:
        default: Enter WebServer 2 Id
      pmSG:
        default: Enter ALB security group
Parameters:
  pmCustomer:
    Type: String
    Default: ACME
  pmProject:
    Type: String
    Default: AWS-Networkiong-Demo
  pmEnvironment:
    Type: String
    Default: DEV
  pmVpc:
    Type: AWS::EC2::VPC::Id
  pmPublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  pmWebServer1:
    Type: AWS::EC2::Instance::Id
  pmWebServer2:
    Type: AWS::EC2::Instance::Id
  pmSG:
    Type: AWS::EC2::SecurityGroup::Id
Mappings: {}
Resources:
  ALBTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      HealthCheckPath: /index.php
      HealthCheckPort: 80
      Name: Default
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: !Ref 'pmVpc'
      Targets:
        - Id: !Ref 'pmWebServer1'
          Port: 80
        - Id: !Ref 'pmWebServer2'
          Port: 80
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: ACME-ALB-DEV
      Scheme: internet-facing
      SecurityGroups:
        - !Ref 'pmSG'
      Subnets: !Ref 'pmPublicSubnets'
      Tags:
        - Key: Customer
          Value: !Ref 'pmCustomer'
        - Key: Project
          Value: !Ref 'pmProject'
        - Key: Environment
          Value: !Ref 'pmEnvironment'
        - Key: Name
          Value: !Sub
            - ${Customer}-${Environment}-ALB
            - Customer: !Ref 'pmCustomer'
              Environment: !Ref 'pmEnvironment'
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref 'ALBTG'
      LoadBalancerArn: !Ref 'ALB'
      Port: '80'
      Protocol: HTTP
Outputs:
  ALB:
    Description: A reference to the Application Load Balancer
    Value: !Ref 'ALB'
  ALBURL:
    Description: The URL of the ALB
    Value: !Join
      - ''
      - - http://
        - !GetAtt 'ALB.DNSName'
  ALBListener:
    Description: A reference to a port 80 listener
    Value: !Ref 'ALBListener'
