AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a VPC with 2 AZ, IGW, NGW, Bastians, Web Servers, and ALB.
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:  
      TemplateURL: https://acme-networking-demo.s3.amazonaws.com/vpc.yaml
      Parameters:
        pmCustomer: ACME
        pmProject: ACME-Networkiong-Demo
        pmEnvironment: DEV
        pmVpcRegion: us-east-1
        pmAz1: us-east-1a
        pmAz2: us-east-1b
        pmVpcCidr: 11.0.0.0/16
        pmPubSubnet1Cidr: 11.0.10.0/24
        pmPubSubnet2Cidr: 11.0.20.0/24
        pmPriSubnet1Cidr: 11.0.50.0/24
        pmPriSubnet2Cidr: 11.0.60.0/24
  SG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://acme-networking-demo.s3.amazonaws.com/sg.yaml
      Parameters:
        pmCustomer: !GetAtt 'VPC.Outputs.Customer'
        pmProject: !GetAtt 'VPC.Outputs.Project'
        pmEnvironment: !GetAtt 'VPC.Outputs.Environment'
        pmVpc: !GetAtt 'VPC.Outputs.VPC'
  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://acme-networking-demo.s3.amazonaws.com/ec2.yaml
      Parameters:
        pmCustomer: !GetAtt 'VPC.Outputs.Customer'
        pmProject: !GetAtt 'VPC.Outputs.Project'
        pmEnvironment: !GetAtt 'VPC.Outputs.Environment'
        pmVpcRegion: !GetAtt 'VPC.Outputs.Region'
        pmPublicSubnet1: !GetAtt 'VPC.Outputs.PublicSubnet1'
        pmPublicSubnet2: !GetAtt 'VPC.Outputs.PublicSubnet2'
        pmPrivateSubnet1: !GetAtt 'VPC.Outputs.PrivateSubnet1'
        pmPrivateSubnet2: !GetAtt 'VPC.Outputs.PrivateSubnet2'
        pmEc2ImageId: ami-0b5eea76982371e91
        pmEc2InstanceType: t2.micro
        pmEc2VolumeSize: '5'
        pmAccessKeyId: aws_cory1
        pmDMZSG: !GetAtt 'SG.Outputs.DMZSG'
        pmWEBSG: !GetAtt 'SG.Outputs.WEBSG'
  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://acme-networking-demo.s3.amazonaws.com/alb.yaml
      Parameters:
        pmCustomer: !GetAtt 'VPC.Outputs.Customer'
        pmProject: !GetAtt 'VPC.Outputs.Project'
        pmEnvironment: !GetAtt 'VPC.Outputs.Environment'
        pmVpc: !GetAtt 'VPC.Outputs.VPC'
        pmPublicSubnets: !GetAtt 'VPC.Outputs.PublicSubnets'
        pmWebServer1: !GetAtt 'EC2.Outputs.WebServer1'
        pmWebServer2: !GetAtt 'EC2.Outputs.WebServer2'
        pmSG: !GetAtt 'SG.Outputs.ALBSG'
Outputs:
  WebSiteURL:
    Description: The URL endpoint for the website service
    Value: !Join
      - ''
      - - !GetAtt 'ALB.Outputs.ALBURL'
        - /
