AWSTemplateFormatVersion : 2010-09-09
Description : Deploy a Bastion server

Parameters:
    BastionAMI:
        Description: AMI Id for the Bastion host.
        Type: AWS::EC2::Image::Id
        Default: ami-0b5eea76982371e91
    BastionSecurityGroup:
      Type: AWS::EC2::SecurityGroup::Id
    Environment:
        Description: Environment
        Type: String
    KeyName:
        Description: AWS EC2 Key Pair
        Type: AWS::EC2::KeyPair::KeyName
    PublicSubnet:
        Description: Subnet for the bastion host to go into
        Type: AWS::EC2::Subnet::Id
    AssignEIP:
        Description: Used an Elastic IP (select no if temporary or not running full time)
        Type: String
        Default: 'Yes'

Conditions:
    AssignEIP: 
        !Equals [!Ref AssignEIP, 'Yes']
       
Resources:
  BastionInterface:
      Type: AWS::EC2::NetworkInterface
      Properties:
          Description: Bastion Interface
          SubnetId: !Ref PublicSubnet
          GroupSet:
            - !Ref BastionSecurityGroup
          SourceDestCheck: false
          Tags:
            - Key: Name
              Value: !Join ["-", [ACME, !Ref Environment, Interface]]
            - Key: Environment
              Value: !Ref Environment
  BastionInstance:
      Type: AWS::EC2::Instance
      Properties:
          DisableApiTermination: false
          InstanceInitiatedShutdownBehavior: stop
          ImageId: !Ref BastionAMI
          InstanceType: t2.medium
          Monitoring: false
          Tags:
            - Key: Name
              Value: !Join ["-", [ACME, !Ref Environment, Bastion]]
            - Key: Backup
              Value: 'No'
            - Key: Environment
              Value: !Ref Environment
          NetworkInterfaces:
            - NetworkInterfaceId: !Ref BastionInterface
              DeviceIndex: 0
          KeyName: !Ref KeyName
  BastionEIP:
      Type: AWS::EC2::EIP
      Condition: AssignEIP
      Properties:
        Domain: vpc
  EIPAssociationBastion:
      Type: AWS::EC2::EIPAssociation
      Condition: AssignEIP
      Properties:
         AllocationId: !Ref BastionEIP
         NetworkInterfaceId: !Ref BastionInterface
