AWSTemplateFormatVersion: 2010-09-09
Description: Deploy IAM resource role and EC2 instance profile

Parameters:
    EnableFlowLogs:
        Description: Enable VPC flow logs
        Type: String
        Default: 'Yes'

Conditions:
    EnableFlowLogs: !Equals [ !Ref EnableFlowLogs, 'Yes' ]

Resources:
  VpcFlowLogsServiceRole:
    Condition: EnableFlowLogs
    Type: AWS::IAM::Role
    Properties:
        AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowFlowLogs
                Effect: Allow
                Principal:
                    Service: vpc-flow-logs.amazonaws.com
                Action: sts:AssumeRole
        Path: /
        Policies:
          - PolicyName: cloudwatchlogsrole
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                  - Action:
                      - logs:CreateLogGroup
                      - logs:CreateLogStream
                      - logs:PutLogEvents
                      - logs:DescribeLogGroups
                      - logs:DescribeLogStreams
                    Effect: Allow
                    Resource: '*'

  EC2InstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ACME_AllEC2IntanceProfile
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/AWSCodeCommitFullAccess
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: EC2InstanceProfileRole
      InstanceProfileName: AllEc2InstanceProfileRole
  EC2InstanceProfilePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: CustomInstanceProfilePolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:PutLogEvents
            Resource: '*'
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:AbortMultipartUpload
              - s3:ListMultipartUploadParts
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
            Resource:
              - arn:aws:s3:::acme-networking-demo
              - arn:aws:s3:::acme-networking-demo/*
      Roles:
        - Ref: EC2InstanceProfileRole

Outputs:
  FlowLogsRole:
    Condition: EnableFlowLogs
    Value: !GetAtt VpcFlowLogsServiceRole.Arn
  EC2InstanceProfile:
    Value: !Ref EC2InstanceProfile