AWSTemplateFormatVersion: 2010-09-09
Description: Provision S3 bucket
Parameters:
  BucketName:
    Description: Name of S3 Bucket
    Type: String
    Default: acme-s3-bucket-delete-me
  CustomerName:
    Description: Name of the customer
    Type: String
    Default: ACME
  EnableVersioning:
    Description: Enable versioning on the S3 Bucket
    Type: String
    AllowedValues:
      - Enabled
      - Suspended
    Default: Suspended
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !Ref EnableVersioning
      Tags:
        - Key: Name
          Value: !Ref BucketName
        - Key: Client
          Value: !Ref CustomerName
Outputs:
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref S3Bucket
  BucketARN:
    Description: S3 Bucket ARN
    Value: !GetAtt S3Bucket.Arn
