AWSTemplateFormatVersion: '2010-09-09'
Description: Provision example users and groups (e.g. Test, Dev, DBA, SysAdmin, Security, etc.)
Resources:
  TestUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: TestUser1
      Path: /
  TestGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: TestGroup
      Path: /
      Policies:
        - PolicyName: TEST-POLICY
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: ''
                Effect: Deny
                Action: ec2:RunInstances
                Condition:
                  StringNotLike:
                    ec2:InstanceType:
                      - t1.*
                      - t2.*
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
  AddTestUsersToTestGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'TestGroup'
      Users:
        - !Ref 'TestUser1'
  DevUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: DevUser1
      Path: /
  DevGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: DevGroup
      Path: /
      Policies:
        - PolicyName: DEV-POLICY
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: ''
                Effect: Deny
                Action: ec2:RunInstances
                Condition:
                  StringNotLike:
                    ec2:InstanceType:
                      - t1.*
                      - t2.*
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/AmazonESFullAccess
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
  AddDevUsersToDevGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'DevGroup'
      Users:
        - !Ref 'DevUser1'
  DataEngineerUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: DataEngineerUser1
      Path: /
  DataGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: DataGroup
      Path: /
      Policies: []
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/DataScientist
  AddDataEngineersToDataGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'DataGroup'
      Users:
        - !Ref 'DataEngineerUser1'
  PowerUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: PowerUser1
      Path: /
  PowerGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: PowerGroup
      Path: /
      Policies: []
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
  AddPowerUsersToPowerGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'PowerGroup'
      Users:
        - !Ref 'PowerUser1'
  DbaUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: DbaUser1
      Path: /
  DbaGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: DbaGroup
      Path: /
      Policies: []
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/DatabaseAdministrator
  AddDbaUsersToDbaGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'DbaGroup'
      Users:
        - !Ref 'DbaUser1'
  SysAdminUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: SysAdminUser1
      Path: /
  SysAdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: SysAdminGroup
      Path: /
      Policies: []
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/SystemAdministrator
  AddSysAdminUsersToSysAdminGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'SysAdminGroup'
      Users:
        - !Ref 'SysAdminUser1'
  SupportUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: SupportAUser1
      Path: /
  SupportGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: SupportGroup
      Path: /
      Policies: []
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/SupportUser
  AddSupportUsersToSupportGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'SupportGroup'
      Users:
        - !Ref 'SupportUser1'
  SecurityAuditUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: SecurityAuditUser1
      Path: /
  SecurityAuditGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: SecurityAuditGroup
      Path: /
      Policies: []
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
  AddSecurityAuditUsersToSecurityAuditGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'SecurityAuditGroup'
      Users:
        - !Ref 'SecurityAuditUser1'
  AdminUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: AdminUser1
      Path: /
  AdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: AdminGroup
      Path: /
      Policies: []
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  AddAdminUsersToAdminGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'AdminGroup'
      Users:
        - !Ref 'AdminUser1'
